In [1]:
# 클래스로 모델 구현

In [ ]:
# model=nn.Linear(1,1)
"""
상속

붕어빵기계(너비=10,높이=5,내용물=단팥,굽는다(1분),...부모 클래스: 메서드, 속성, 내부클래스)
#agile기법:허접하더라도 빠르게 만듬->배포(time to market)  release..
상속
잉어빵기계(자식 클래스)

요구분석 설계 구현 테스트 배포 유지보수
"""

In [1]:
"""
동물(부모)
    파충류,    양서류, 포유류, 조류, ...
       뱀, 개구리, ... 사람(먹는다)#먹는다라는메서드->씹어먹는다 (상속받은 메서드 재정의(overriding))
      독사,살모사,...
"""

In [9]:
import torch.nn as nn
import torch
import torch.nn.functional as F

In [15]:
class LinearRegressionModel(nn.Module):  # Module:부모클래스, LinearRegressionModel:자식클래스 # 클래스 예약어 쓰고 뒤에 클래스 이름작성
    def __init__(self): # LinearRegressionModel클래스 객체가 생성될 때 자동 호출
        super().__init__()  # super는 부모 -> nn.Module 부모가 가지고 있는 init함수 호출 = 부모 객체가 만들어짐 의미
                            # 부모 클래스의 속성이 초기화된다
        self.linear=nn.Linear(1,1) #인풋 1, 출력1
        #print("__init__호출됨")
    def forward(self, x):
        return self.linear(x)

In [16]:
LinearRegressionModel()

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

In [17]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [18]:
model=LinearRegressionModel()

In [19]:
optimizer=torch.optim.SGD(model.parameters(), lr=0.01)

In [20]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31.696798
Epoch  100/2000 Cost: 0.013848
Epoch  200/2000 Cost: 0.008558
Epoch  300/2000 Cost: 0.005288
Epoch  400/2000 Cost: 0.003268
Epoch  500/2000 Cost: 0.002019
Epoch  600/2000 Cost: 0.001248
Epoch  700/2000 Cost: 0.000771
Epoch  800/2000 Cost: 0.000476
Epoch  900/2000 Cost: 0.000294
Epoch 1000/2000 Cost: 0.000182
Epoch 1100/2000 Cost: 0.000112
Epoch 1200/2000 Cost: 0.000069
Epoch 1300/2000 Cost: 0.000043
Epoch 1400/2000 Cost: 0.000027
Epoch 1500/2000 Cost: 0.000016
Epoch 1600/2000 Cost: 0.000010
Epoch 1700/2000 Cost: 0.000006
Epoch 1800/2000 Cost: 0.000004
Epoch 1900/2000 Cost: 0.000002
Epoch 2000/2000 Cost: 0.000001


In [ ]:
"""
미니 배치 : 대규모 데이터를 작은 단위로 나누어 연산
ex) 데이터 100건
1에폭 :100건의 데이터를 모두 한번 학습
20 배치사이즈 : 한번에 20건의 데이터를 읽어서 학습(w, b의 업데이트 횟수)
5 배치(미니배치): 20배치 사이즈로 데이터를 5번 가져와서 학습 ->100건 데이터 학습
이터레이션: 1에폭에서 발생하는 w, b의 업데이트 횟수 (배치를 할때마다 w, b에대해서 업데이트한다 =이터레이션 5다)
배치학습: 전체 데이터에 대해 한 번에 배치와 함께 업데이트를 수행하는경우
미니배치 학습: 전체 데이터에 대해 여러번 배치 및 업데이트 수행(대부분이 미니배치학습이다)
파이토치에서는 데이터셋(DataSet), 데이터로더(DataLoader)를 제공
-> 데이터 셔플, 미니배치 학습, 병렬 처리 등의 연산을 빠르게 할 수 있음
"""

In [21]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [22]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [23]:
model = MultivariateLinearRegressionModel()

In [24]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [25]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 7219.150879
Epoch  100/2000 Cost: 1.260782
Epoch  200/2000 Cost: 1.214891
Epoch  300/2000 Cost: 1.171364
Epoch  400/2000 Cost: 1.130078
Epoch  500/2000 Cost: 1.090934
Epoch  600/2000 Cost: 1.053779
Epoch  700/2000 Cost: 1.018554
Epoch  800/2000 Cost: 0.985112
Epoch  900/2000 Cost: 0.953384
Epoch 1000/2000 Cost: 0.923298
Epoch 1100/2000 Cost: 0.894732
Epoch 1200/2000 Cost: 0.867619
Epoch 1300/2000 Cost: 0.841874
Epoch 1400/2000 Cost: 0.817447
Epoch 1500/2000 Cost: 0.794261
Epoch 1600/2000 Cost: 0.772240
Epoch 1700/2000 Cost: 0.751333
Epoch 1800/2000 Cost: 0.731472
Epoch 1900/2000 Cost: 0.712610
Epoch 2000/2000 Cost: 0.694686


In [ ]:
#데이터 로드

In [26]:
from torch.utils.data import TensorDataset # 텐서데이터셋
from torch.utils.data import DataLoader # 데이터로더

In [27]:
x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  90],
                               [96,  98,  100],
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [28]:
dataset=TensorDataset(x_train, y_train)
#TensorDataset: 텐서 데이터를 전달받아 데이터셋(Dataset) 형태로 변환

In [ ]:
#시계열 데이터는 셔플하면안된다.
#시계열이 아닌이상 배치를 할 때 마다 셔플을 해주는게 좋다, 편협적인 모델방지

In [29]:
dataloader=DataLoader(dataset, batch_size=2, shuffle=True)

In [30]:
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [31]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 21357.650391
Epoch    0/20 Batch 2/3 Cost: 2558.858887
Epoch    0/20 Batch 3/3 Cost: 1703.676758
Epoch    1/20 Batch 1/3 Cost: 335.024170
Epoch    1/20 Batch 2/3 Cost: 320.329315
Epoch    1/20 Batch 3/3 Cost: 24.254452
Epoch    2/20 Batch 1/3 Cost: 16.706713
Epoch    2/20 Batch 2/3 Cost: 4.690706
Epoch    2/20 Batch 3/3 Cost: 19.000559
Epoch    3/20 Batch 1/3 Cost: 1.479723
Epoch    3/20 Batch 2/3 Cost: 4.302562
Epoch    3/20 Batch 3/3 Cost: 8.427320
Epoch    4/20 Batch 1/3 Cost: 5.503664
Epoch    4/20 Batch 2/3 Cost: 2.175368
Epoch    4/20 Batch 3/3 Cost: 7.631390
Epoch    5/20 Batch 1/3 Cost: 3.640933
Epoch    5/20 Batch 2/3 Cost: 4.815210
Epoch    5/20 Batch 3/3 Cost: 8.008478
Epoch    6/20 Batch 1/3 Cost: 5.603683
Epoch    6/20 Batch 2/3 Cost: 4.845184
Epoch    6/20 Batch 3/3 Cost: 0.245428
Epoch    7/20 Batch 1/3 Cost: 6.088913
Epoch    7/20 Batch 2/3 Cost: 1.566657
Epoch    7/20 Batch 3/3 Cost: 4.689641
Epoch    8/20 Batch 1/3 Cost: 3.060696
Epoch   

In [32]:
new_var =  torch.FloatTensor([[73, 80, 75]])

In [33]:
pred_y=model(new_var)

In [34]:
pred_y

tensor([[155.0729]], grad_fn=<AddmmBackward0>)

In [36]:
# class CustomDataset(torch.utils.data.Dataset):
#   def __init__(self):

#   def __len__(self):

#   def __getitem__(self, idx):

In [37]:
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [38]:
class CustomDataset(Dataset):
  def __init__(self):
    self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_data = [[152], [185], [180], [196], [142]]

  # 총 데이터의 개수를 리턴
  def __len__(self):
    return len(self.x_data)

  # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
  def __getitem__(self, idx):
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y

In [39]:
dataset = CustomDataset()

In [40]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [41]:
model = torch.nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [44]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 2.717707
Epoch    0/20 Batch 2/3 Cost: 3.956150
Epoch    0/20 Batch 3/3 Cost: 0.710241
Epoch    1/20 Batch 1/3 Cost: 1.830064
Epoch    1/20 Batch 2/3 Cost: 2.518311
Epoch    1/20 Batch 3/3 Cost: 0.361235
Epoch    2/20 Batch 1/3 Cost: 3.044295
Epoch    2/20 Batch 2/3 Cost: 3.324387
Epoch    2/20 Batch 3/3 Cost: 0.046710
Epoch    3/20 Batch 1/3 Cost: 3.401094
Epoch    3/20 Batch 2/3 Cost: 1.072395
Epoch    3/20 Batch 3/3 Cost: 0.199051
Epoch    4/20 Batch 1/3 Cost: 1.714315
Epoch    4/20 Batch 2/3 Cost: 2.545219
Epoch    4/20 Batch 3/3 Cost: 0.843451
Epoch    5/20 Batch 1/3 Cost: 3.674503
Epoch    5/20 Batch 2/3 Cost: 2.452929
Epoch    5/20 Batch 3/3 Cost: 0.291280
Epoch    6/20 Batch 1/3 Cost: 1.325727
Epoch    6/20 Batch 2/3 Cost: 2.530401
Epoch    6/20 Batch 3/3 Cost: 2.742608
Epoch    7/20 Batch 1/3 Cost: 1.756152
Epoch    7/20 Batch 2/3 Cost: 0.739915
Epoch    7/20 Batch 3/3 Cost: 6.590749
Epoch    8/20 Batch 1/3 Cost: 2.247971
Epoch    8/20 Batch 2/3 C

In [ ]:
logits = model(encoding['input_ids'], token_type_ids=encoding['token_type_ids'])[0]
softmax = tf.keras.layers.Softmax()
probs = softmax(logits)
print(probs)

In [ ]:
# https://wikidocs.net/156176

In [ ]:
###TPU

In [1]:
import tensorflow as tf
import os

resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])

tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)

In [2]:
strategy = tf.distribute.TPUStrategy(resolver) # 분산 처리와 관련된

In [3]:
def create_model(): # TPU를 사용할 때  기존의 모델구조를 리스트에 담고, 함수를 만들어라
  return tf.keras.Sequential(
      [tf.keras.layers.Conv2D(256, 3, activation='relu', input_shape=(28, 28, 1)),
       tf.keras.layers.Conv2D(256, 3, activation='relu'),
       tf.keras.layers.Flatten(),
       tf.keras.layers.Dense(256, activation='relu'),
       tf.keras.layers.Dense(128, activation='relu'),
       tf.keras.layers.Dense(10)])

In [4]:
with strategy.scope(): # with구문안에 모델 생성코드 써주고, 모델 컴파일..
  model = create_model() # TPU를 사용할 때 함수를 호출하는형식으로 모델을 호출함
  model.compile(optimizer='adam',
                loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                metrics=['sparse_categorical_accuracy'])

In [ ]:
# BERT, TPU, 네이버 영화 댓글 분류기

In [5]:
pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 15.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 30.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 35.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 40.4 MB/s eta 0:00:00


In [6]:
import transformers

In [7]:
import pandas as pd
import numpy as np
import urllib.request
import os
from tqdm import tqdm
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel

In [8]:
urllib.request.urlretrieve("https://raw.githubusercontent.com/e9t/nsmc/master/ratings_train.txt", filename="ratings_train.txt")
urllib.request.urlretrieve("https://raw.githubusercontent.com/e9t/nsmc/master/ratings_test.txt", filename="ratings_test.txt")

('ratings_test.txt', <http.client.HTTPMessage at 0x7dafd0200100>)

In [9]:
train_data = pd.read_table('ratings_train.txt')
test_data = pd.read_table('ratings_test.txt')

In [10]:
print('훈련용 리뷰 개수 :',len(train_data)) # 훈련용 리뷰 개수 출력

훈련용 리뷰 개수 : 150000


In [11]:
print('테스트용 리뷰 개수 :',len(test_data)) # 테스트용 리뷰 개수 출력

테스트용 리뷰 개수 : 50000


In [12]:
train_data[:5]

id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [13]:
train_data = train_data.dropna(how = 'any') # Null 값이 존재하는 행 제거
train_data = train_data.reset_index(drop=True)
print(train_data.isnull().values.any()) # Null 값이 존재하는지 확인

False


In [14]:
len(train_data) # null이 5개있었다

149995

In [15]:
test_data = test_data.dropna(how = 'any') # Null 값이 존재하는 행 제거
test_data = test_data.reset_index(drop=True)
print(test_data.isnull().values.any()) # Null 값이 존재하는지 확인

False


In [16]:
len(test_data)

49997

In [17]:
train_data.drop_duplicates(subset=['document'], inplace=True)

In [18]:
len(train_data) # 중복된 데이터가 3000여건 있었다

146182

In [20]:
tokenizer=BertTokenizer.from_pretrained("klue/bert-base")

In [ ]:
"""
BERT: 구글104개 이상 국가의 언어로 만든 모델

사전 학습된한국어 bert모델
KorBERT : ETRI, 20gb이상 데이터, 3만개 이상의 한국어 단어
KoBERT, KoBART: SKT
...
KoGPT2: SKT
KoreALBERT: 40GB 이상 데이터
HyperCLOVA: 네이버, 초대규모 모델
KLUE-BERT
KoGPT: 카카오
...

In [21]:
print(tokenizer.tokenize("보는내내 그대로 들어맞는 예측 카리스마 없는 악역"))

['보', '##는', '##내', '##내', '그대로', '들어맞', '##는', '예측', '카리스마', '없', '##는', '악역']


In [22]:
print(tokenizer.encode("보는내내 그대로 들어맞는 예측 카리스마 없는 악역"))

[2, 1160, 2259, 2369, 2369, 4311, 20657, 2259, 5501, 13132, 1415, 2259, 23713, 3]


In [24]:
# 2: cls, 3:sep
print(tokenizer.decode(tokenizer.encode("보는내내 그대로 들어맞는 예측 카리스마 없는 악역1")))

[CLS] 보는내내 그대로 들어맞는 예측 카리스마 없는 악역1 [SEP]


In [25]:
tokenizer.pad_token_id

0

In [26]:
max_seq_len = 128

In [27]:
encoded_result = tokenizer.encode(" 전율을         일으키는         영화 . 다시         보고싶은   영화 "
, max_length=max_seq_len, pad_to_max_length=True)

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2614: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(


In [28]:
encoded_result

[2,
 1537,
 2534,
 2069,
 6572,
 2259,
 3771,
 18,
 3690,
 4530,
 2585,
 2073,
 3771,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [30]:
# 정수 인코딩, 세그먼트 인코딩, 어텐션 마스크

# 세그먼트 인코딩
[0]*max_seq_len

# 어텐션 마스크: 토큰 위치는 1, 패딩 위치는 0
tokenizer.encode("전율을 일으키는 영화. 다시 보고싶은 영화")

[2, 1537, 2534, 2069, 6572, 2259, 3771, 18, 3690, 4530, 2585, 2073, 3771, 3]

In [31]:
valid_num = len(tokenizer.encode("전율을 일으키는 영화. 다시 보고싶은 영화"))
print(valid_num * [1] + (max_seq_len - valid_num) * [0])

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [33]:
def convert_examples_to_features(examples, labels, max_seq_len, tokenizer): # examples에 댓글들어감,
#                                 댓글      긍/부     128        tokenizer
#           아 더빙.. 진짜 짜증나네요 목소리	 0
    input_ids, attention_masks, token_type_ids, data_labels = [], [], [], []

    for example, label in tqdm(zip(examples, labels), total=len(examples)):
        # input_id는 워드 임베딩을 위한 문장의 정수 인코딩
        input_id = tokenizer.encode(example, max_length=max_seq_len, pad_to_max_length=True)

        # attention_mask는 실제 단어가 위치하면 1, 패딩의 위치에는 0인 시퀀스.
        padding_count = input_id.count(tokenizer.pad_token_id)
        attention_mask = [1] * (max_seq_len - padding_count) + [0] * padding_count

        # token_type_id는 세그먼트 임베딩을 위한 것으로 이번 예제는 문장이 1개이므로 전부 0으로 통일.
        token_type_id = [0] * max_seq_len
        assert len(input_id) == max_seq_len, "Error with input length {} vs {}".format(len(input_id), max_seq_len)
        assert len(attention_mask) == max_seq_len, "Error with attention mask length {} vs {}".format(len(attention_mask), max_seq_len)
        assert len(token_type_id) == max_seq_len, "Error with token type length {} vs {}".format(len(token_type_id), max_seq_len)

        input_ids.append(input_id)
        attention_masks.append(attention_mask)
        token_type_ids.append(token_type_id)
        data_labels.append(label)

    input_ids = np.array(input_ids, dtype=int)
    attention_masks = np.array(attention_masks, dtype=int)
    token_type_ids = np.array(token_type_ids, dtype=int)

    data_labels = np.asarray(data_labels, dtype=np.int32)

    return (input_ids, attention_masks, token_type_ids), data_labels
    #                        train_x                   ,  train_y

In [34]:
train_data

id                                           document  label
0        9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1        3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...          ...                                                ...    ...
149990   6222902                                인간이 문제지.. 소는 뭔죄인가..      0
149991   8549745                                      평점이 너무 낮아서...      1
149992   9311800                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0
149993   2376369                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149994   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[146182 rows x 3 columns]

In [35]:
train_X, train_y = convert_examples_to_features(train_data['document'], train_data['label'], max_seq_len=max_seq_len, tokenizer=tokenizer)

  0%|          | 0/146182 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2614: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(
100%|██████████| 146182/146182 [01:25<00:00, 1715.75it/s]


In [36]:
np.shape(train_X)

(3, 146182, 128)

In [37]:
train_X

(array([[   2, 1376,  831, ...,    0,    0,    0],
        [   2, 1963,   18, ...,    0,    0,    0],
        [   2,    1,    3, ...,    0,    0,    0],
        ...,
        [   2, 4380, 1097, ...,    0,    0,    0],
        [   2, 9300, 3771, ...,    0,    0,    0],
        [   2, 3629, 3771, ...,    0,    0,    0]]),
 array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]))

In [38]:
train_y

array([0, 1, 0, ..., 0, 1, 0], dtype=int32)

In [39]:
test_X, test_y = convert_examples_to_features(test_data['document'], test_data['label'], max_seq_len=max_seq_len, tokenizer=tokenizer)

  0%|          | 0/49997 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2614: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(
100%|██████████| 49997/49997 [00:25<00:00, 1930.61it/s]


In [40]:
train_X[0][0] #첫번째 문장에 대한 input id

array([   2, 1376,  831, 2604,   18,   18, 4229, 9801, 2075, 2203, 2182,
       4243,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0])

In [41]:
train_X[1][0] #첫번째 문장에 대한 어텐션마스크

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
train_X[2][0] #첫번째 문장에 대한 세그먼트

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
tokenizer.decode(train_X[0][0])

'[CLS] 아 더빙.. 진짜 짜증나네요 목소리 [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]'

In [48]:
# 최대 길이: 128
input_id = train_X[0][0]
attention_mask = train_X[1][0]
token_type_id = train_X[2][0]
label = train_y[0]

print('단어에 대한 정수 인코딩 :',input_id)
print('어텐션 마스크 :',attention_mask)
print('세그먼트 인코딩 :',token_type_id)
print('각 인코딩의 길이 :', len(input_id))
print('정수 인코딩 복원 :',tokenizer.decode(input_id))
print('레이블 :',label)

단어에 대한 정수 인코딩 : [   2 1376  831 2604   18   18 4229 9801 2075 2203 2182 4243    3    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0]
어텐션 마스크 : [1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
세그먼트 인코딩 : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [49]:
model = TFBertModel.from_pretrained("klue/bert-base", from_pt=True)
#                   이미학습되어져있는 모델

pytorch_model.bin:   0%|          | 0.00/445M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'bert.embeddings.position_ids', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the 

In [50]:
max_seq_len = 128

In [51]:
input_ids_layer = tf.keras.layers.Input(shape=(max_seq_len,), dtype=tf.int32)
attention_masks_layer = tf.keras.layers.Input(shape=(max_seq_len,), dtype=tf.int32)
token_type_ids_layer = tf.keras.layers.Input(shape=(max_seq_len,), dtype=tf.int32)

outputs = model([input_ids_layer, attention_masks_layer, token_type_ids_layer])

In [54]:
print(outputs[0])
# 만들고자 하는 모델이 다:다 구조인 경우에는 outputs[0]사용
# shape=(None, 128, 768) #128개의 단어가 있는데 768차원
#       (배치크기, 문장길이, 단어벡터)
# 768차원 벡터가 128개 있다

KerasTensor(type_spec=TensorSpec(shape=(None, 128, 768), dtype=tf.float32, name=None), name='tf_bert_model/bert/encoder/layer_._11/output/LayerNorm/batchnorm/add_1:0', description="created by layer 'tf_bert_model'")


In [55]:
print(outputs[1])
# 만들고자 하는 모델이 다:1 구조인 경우에는 outputs[1]사용
# shape=(None, 768)
#       (배치크기, 단어벡터)
# 768차원 벡터가 1개 있다

KerasTensor(type_spec=TensorSpec(shape=(None, 768), dtype=tf.float32, name=None), name='tf_bert_model/bert/pooler/dense/Tanh:0', description="created by layer 'tf_bert_model'")


In [ ]:
#bert 다:1구조 모델 생성.

In [57]:
class TFBertForSequenceClassification(tf.keras.Model):
    def __init__(self, model_name):  #"model_name=klue/bert-base"
        super(TFBertForSequenceClassification, self).__init__()
        self.bert = TFBertModel.from_pretrained(model_name, from_pt=True)
        self.classifier = tf.keras.layers.Dense(1,
                                                kernel_initializer=tf.keras.initializers.TruncatedNormal(0.02),
                                                activation='sigmoid',
                                                name='classifier')

    def call(self, inputs):
        input_ids, attention_mask, token_type_ids = inputs
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask, token_type_ids=token_type_ids)
        cls_token = outputs[1]
        prediction = self.classifier(cls_token)

        return prediction

# 파인튜닝에서 바꿀거 Dense(1, #이진분류라 1인데 다른 다중구조면 종류만큼 바꿔줘야함, activation='sigmoid'마찬가지,
# 아래함수에서는 cls_token=에 outputs[1]인데 다:1구조라그렇고 다:다 구조면 outputs[0]

In [58]:
# TPU 작동을 위한 코드 TPU 작동을 위한 코드
resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)

In [59]:
strategy = tf.distribute.experimental.TPUStrategy(resolver)

In [61]:
with strategy.scope():
  model = TFBertForSequenceClassification("klue/bert-base")
  optimizer = tf.keras.optimizers.Adam(learning_rate=5e-5)
  loss = tf.keras.losses.BinaryCrossentropy()
  model.compile(optimizer=optimizer, loss=loss, metrics = ['accuracy'])

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'bert.embeddings.position_ids', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the 

In [62]:
model.fit(train_X, train_y, epochs=2, batch_size=64, validation_split=0.2)

Epoch 1/2
1828/1828 [==============================] - 344s 138ms/step - loss: 0.2804 - accuracy: 0.8812 - val_loss: 0.2452 - val_accuracy: 0.9004
Epoch 2/2
1828/1828 [==============================] - 200s 109ms/step - loss: 0.1854 - accuracy: 0.9270 - val_loss: 0.2560 - val_accuracy: 0.9024


In [63]:
results = model.evaluate(test_X, test_y, batch_size=1024)
print("test loss, test acc: ", results)

49/49 [==============================] - 23s 337ms/step - loss: 0.2661 - accuracy: 0.8977
test loss, test acc:  [0.2660754323005676, 0.8976938724517822]


In [ ]:
sentiment_predict("보던거라 계속보고있는데 전개도 느리고 주인공인 은희는 한두컷 나오면서 소극적인모습에 ")

In [ ]:
sentiment_predict("내 친구 홍길동이가 이 영화를 보고 기겁을 하던데?")
sentiment_predict("이것도 영화냐?")

In [64]:
def sentiment_predict(new_sentence):
  input_id = tokenizer.encode(new_sentence, max_length=max_seq_len, pad_to_max_length=True)

  padding_count = input_id.count(tokenizer.pad_token_id)
  attention_mask = [1] * (max_seq_len - padding_count) + [0] * padding_count
  token_type_id = [0] * max_seq_len

  input_ids = np.array([input_id])
  attention_masks = np.array([attention_mask])
  token_type_ids = np.array([token_type_id])

  encoded_input = [input_ids, attention_masks, token_type_ids]
  score = model.predict(encoded_input)[0][0]
  print(score)

  if(score > 0.5):
    print("{:.2f}% 확률로 긍정 리뷰입니다.\n".format(score * 100))
  else:
    print("{:.2f}% 확률로 부정 리뷰입니다.\n".format((1 - score) * 100))

In [65]:
sentiment_predict("보던거라 계속보고있는데 전개도 느리고 주인공인 은희는 한두컷 나오면서 소극적인모습에 ")

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2614: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(


1/1 [==============================] - 12s 12s/step
0.0065027475
99.35% 확률로 부정 리뷰입니다.



In [66]:
sentiment_predict("이것도 영화냐?")

1/1 [==============================] - 1s 1s/step
0.010542095
98.95% 확률로 부정 리뷰입니다.



In [67]:
sentiment_predict("내 친구 홍길동이가 이 영화를 보고 기겁을 하던데?")


1/1 [==============================] - 1s 1s/step
0.3579529
64.20% 확률로 부정 리뷰입니다.



In [72]:
sentiment_predict("정말 추...천.... 합니다...")

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2614: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(


1/1 [==============================] - 2s 2s/step
0.019011915
98.10% 확률로 부정 리뷰입니다.

