In [ ]:
"""
딥러닝 프레임웍
파이토치, 텐서플로우

파이토치
https://tutorials.pytorch.kr/?_gl=1*1f3w7gi*_ga*NTQxMTA4OTQuMTY1NzM0MzMzMA..*_ga_LEHG248408*MTY1ODA2Mzg0NS4zLjEuMTY1ODA2Mzg0OC41Nw

PyTorch에는 두가지 주요한 특징이 있습니다:
NumPy와 유사하지만 GPU 상에서 실행 가능한 n-차원 텐서(Tensor)(텐서는 배열이라고 생각할 수 있다)
1차원 구조로 구성된 값을 벡터라고 하고 2차원으로 구성된 값을 행렬 3차원부터는 다차원행렬, 텐서라고 한다
신경망을 구성하고 학습하는 과정에서의 자동 미분(Automatic differentiation)

2차원 텐서(batch size, dim)
비전 분야(이미지, 영상)에서는 3차원텐서 주로사용
(batch size, width, height)

자연어처리쪽에서는 3차원이지만
(batch size, length, dimention)
"""

In [7]:
import numpy as np

In [8]:
#넘파이로 텐서를 만드는 방법

In [12]:
#1차원 텐서(일단 리스트를만든다 - np.array())
t=np.array([1,2,3,4])
t.ndim #몇 차원 텐서인지 확인하는법
t.shape #텐서의 크기 (4,)는 (1,4)를 의미함

(4,)

In [17]:
#2차원 텐서
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
t.ndim #몇 차원 텐서
t.shape #텐서의 크기(4, 3)

(4, 3)

In [ ]:
# 파이토치로 텐서를 만드는 방법

In [19]:
pip install torch

   ---------------------------------------- 0.0/192.3 MB ? eta -:--:--
   ---------------------------------------- 2.1/192.3 MB 68.7 MB/s eta 0:00:03
    --------------------------------------- 4.5/192.3 MB 71.2 MB/s eta 0:00:03
   - -------------------------------------- 7.3/192.3 MB 77.9 MB/s eta 0:00:03
   -- ------------------------------------- 10.2/192.3 MB 72.0 MB/s eta 0:00:03
   -- ------------------------------------- 13.3/192.3 MB 81.8 MB/s eta 0:00:03
   --- ------------------------------------ 16.6/192.3 MB 81.8 MB/s eta 0:00:03
   ---- ----------------------------------- 19.7/192.3 MB 81.8 MB/s eta 0:00:03
   ---- ----------------------------------- 21.1/192.3 MB 81.8 MB/s eta 0:00:03
   ---- ----------------------------------- 22.0/192.3 MB 65.2 MB/s eta 0:00:03
   ---- ----------------------------------- 22.0/192.3 MB 65.2 MB/s eta 0:00:03
   ---- ----------------------------------- 22.0/192.3 MB 65.2 MB/s eta 0:00:03
   ---- ----------------------------------- 23.4/192

In [20]:
import torch

In [21]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
t
#클래스(FloatTensor): 대문자로 시작
#클래스에서 뒤에 ()괄호해주면 객체가 생성

tensor([0., 1., 2., 3., 4., 5., 6.])

In [24]:
t.dim()
t.shape #속성 #크기알수있다
t.size() #함수(메서드), 내차.달린다() 자동차(클래스) #크기알수있다
#'자동차' 클래스(class)로부터 파생(생성)된 실체(객체)가 '내차'

torch.Size([7])

In [ ]:
"""
클래스 정의하는법
class FloatTensor:
    속성(특성) ex)자동차가 가지고있는 특성: 배기량, 연비, 등등..
    shape = len([0., 1., 2., 3., 4., 5., 6.])
    함수(동작) ex)달린다..
    size():
        return len([0., 1., 2., 3., 4., 5., 6.])
    ...
"""

In [ ]:
#클래스: 설계도면, 붕어빵 기계, 벽돌공장, ...
#객체: 클래스로부터 생성되는 실체
#설계도면 -> 실제건물
#붕어빵기계 -> 붕어빵
#벽돌공장 -> 벽돌
#메서드: 객체가 수행하는 동작(기능)
#속성(어트리뷰트): 객체의 특성
#객체지향(적) 프로그래밍: 

# ex) 절차지향적 사례(과거)
# - 붕어빵기계로 붕어빵을 판매하던 시대가 지나가고
# 잉어빵 시대가 도래, 붕어빵기게는 못쓰게 됨 -> 잉어빵 기계를 새롭게 제작

# ex) 객체지향적 사례(현재~미래)(비용절감, 프로그램 안정적, 개발시간단축)
# - 붕어빵기계로 붕어빵을 판매하던 시대가 지나가고
# 잉어빵 시대가 도래, 붕어빵기계를 재사용(붕어빵기계의 메서드, 속성 중에서 그대로 사용할 것은 사용하고,
# 변경할 것은 변경, 버릴 것은 버리고)

In [25]:
t

tensor([0., 1., 2., 3., 4., 5., 6.])

In [28]:
t[2:5]

tensor([2., 3., 4.])

In [29]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])

In [38]:
t.dim()
t.size()
t[:,1] #첫번째차원은 전부다 가지고오고, 두번째는 1

tensor([ 2.,  5.,  8., 11.])

In [40]:
t[:,1].size()

torch.Size([4])

In [ ]:
# 행렬 연산(덧셈,뺄셈): 두 행렬의 크기가 같아야 함
# 행렬 연산(곱셈): 두 행렬의 마지막 차원과 첫번째 차원이 일치
# 브로드캐스팅: 크기를 맞춰서 연산이가능하도록

In [41]:
t1 = torch.FloatTensor([1,1])
t2 = torch.FloatTensor([2,2])

In [43]:
t1.shape
t1+t2

tensor([3., 3.])

In [44]:
t3=torch.FloatTensor([1,1]) #(1,2)
t4=torch.FloatTensor([3]) #자동 변경(브로드캐스팅) (1,) -> (1,2)

In [45]:
t3+t4

tensor([4., 4.])

In [48]:
# 2x1  +  1x2
t5=torch.FloatTensor([[1,3]]) #[[1,3],
                              #[1,3]]
t6=torch.FloatTensor([[1],[3]])
#[[1],         [[1],[1],
#[3]]          [3],[3]]

#자동으로 브로드캐스팅해줘서 잘못된지 모르는경우가 있다 주의!!!

In [49]:
t5.shape

torch.Size([1, 2])

In [50]:
t6.shape

torch.Size([2, 1])

In [51]:
t5+t6

tensor([[2., 4.],
        [4., 6.]])

In [52]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

In [53]:
m1.shape

torch.Size([2, 2])

In [54]:
m2.shape

torch.Size([2, 1])

In [55]:
m1.matmul(m2) #행렬의 곱셈

tensor([[ 5.],
        [11.]])

In [56]:
m1*m2 #브로드캐스팅 돼서 행렬의 요소간 곱셈

tensor([[1., 2.],
        [6., 8.]])

In [57]:
t=torch.FloatTensor([[1,2],[3,4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [58]:
t.mean()

tensor(2.5000)

In [62]:
t.mean(dim=0) #dim=0은 첫번째 차원, 행렬에서는 행, 행에 해당하는 차원을 제거하겠다는 의미
# (2,2) -> (2,3)
#dim=1은 두번째 차원, 행렬에서는 열, 열을 제거 -> 행만남음

tensor([2., 3.])

In [63]:
t=torch.FloatTensor([[1,2],[3,4]])

In [64]:
t.sum()

tensor(10.)

In [65]:
t.sum(dim=0) # 행을제거 

tensor([4., 6.])

In [66]:
t.sum(dim=1)

tensor([3., 7.])

In [67]:
t.sum(dim=-1) #마지막 차원 제거(열 제거)

tensor([3., 7.])

In [70]:
t

tensor([[1., 2.],
        [3., 4.]])

In [68]:
t.max()

tensor(4.)

In [69]:
t.max(dim=0) #행 제거, indices(argmax): 최대값의 인덱스

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [73]:
import numpy as np

In [74]:
import torch

In [75]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [76]:
ft.shape

torch.Size([2, 2, 3])

In [77]:
ft.view([-1,3]) #view:텐서 크기 변경, (-1,3)은 (?,3)로 표기하기도 함
#[2, 2, 3] 3차원 텐서를 2차원 텐서로 변경(-1, 3)
#12개 요소로 구성된 3차원 텐서 -> 열의수 3으로 고정, 행은 자연스럽게 4 => (4,3)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [78]:
ft.view([4,3])

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [79]:
#ft.view([-1,5]) => 약수(나누어 떨어지지가않음) 에러남
ft.view([4,-1])

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [81]:
ft #(2,2,3) -> (?,1,3)
ft.view([-1,1,3])

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])

In [82]:
ft=torch.FloatTensor([[0],[1],[2]])
ft# 3*1행렬

tensor([[0.],
        [1.],
        [2.]])

In [83]:
ft.squeeze() #크기가 1인 차원을 제거, 2차원 =>1차원

tensor([0., 1., 2.])

In [84]:
ft2=torch.FloatTensor([[0,1],[1,2],[2,3]])
ft2

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

In [85]:
ft2.squeeze() # 행 크기:3, 열 크기:2 => 크기가 1인 차원이 없으므로 제거작업 수행하지 않음

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

In [ ]:
# unsqueeze: 크기가 1인 차원을 특정 위치에 추가

In [86]:
ft = torch.Tensor([0, 1, 2])
ft

tensor([0., 1., 2.])

In [87]:
ft.unsqueeze(0) #(1,3)

tensor([[0., 1., 2.]])

In [88]:
ft.unsqueeze(1) #(3,1)

tensor([[0.],
        [1.],
        [2.]])

In [ ]:
# https://pytorch.org/docs/stable/tensors.html

In [89]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [90]:
lt = torch.LongTensor([1., 2, 3, 4]) #실수 정수 존재할때에는 정수로통합
print(lt)

tensor([1, 2, 3, 4])


In [91]:
lt.float()

tensor([1., 2., 3., 4.])

In [92]:
bt = torch.ByteTensor([True, False, True, False])
print(bt)

tensor([1, 0, 1, 0], dtype=torch.uint8)


In [94]:
bt.long()

tensor([1, 0, 1, 0])

In [95]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [96]:
x

tensor([[1., 2.],
        [3., 4.]])

In [97]:
y

tensor([[5., 6.],
        [7., 8.]])

In [101]:
torch.cat([x,y], dim=0) #첫번째 차원을 기준으로 연결됨

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [102]:
torch.cat([x,y], dim=1) #두번째 차원을 기준으로 연결됨

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [ ]:
#딥러닝시 중간중간 서로 다른 텐서를 연결하는 경우가 있는데 그런경우 사용.

In [105]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [107]:
z

tensor([3., 6.])

In [108]:
torch.stack([x, z, y])

tensor([[1., 4.],
        [3., 6.],
        [2., 5.]])

In [109]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [112]:
# 텐서의 크기는 그대로 두되, 새롭게 0또는 1로 값을 채우는 것
torch.ones_like(x)
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [113]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [114]:
x

tensor([[1., 2.],
        [3., 4.]])

In [115]:
x*2

tensor([[2., 4.],
        [6., 8.]])

In [116]:
x.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [117]:
x

tensor([[1., 2.],
        [3., 4.]])

In [118]:
x.mul_(2) #함수뒤에 _로 끝나는것 => inplace처럼 업데이트까지해줌

tensor([[2., 4.],
        [6., 8.]])

In [119]:
x

tensor([[2., 4.],
        [6., 8.]])

In [120]:
result = 0 #전역변수: 함수 밖에있는 변수

In [126]:
def add(num):
    global result #전역변수를 사용하겠다
    #result=1 #지역변수: 함수(블록) 내에서만 사용되는 변수
    result +=num
    return result

In [127]:
add(3)

3

In [128]:
print(result) #전역변수 사용해서 함수에서 값을 바꿨기 때문에 3이출력

3


In [137]:
result1 = 0
result2 = 0

In [138]:
def add1(num):
    global result1
    result1 += num
    return result1

In [139]:
def add2(num):
    global result2
    result2 += num
    return result2

In [140]:
print(add1(3))
print(add1(4))

3
7


In [141]:
print(add2(2))
print(add2(6))

2
8


In [145]:
class Calculator:
    def __init__(self): #클래스->객체 생성될때 자동 호출(생성자)
        self.result = 0
        print("생성자 호출됨")

    def add(self, num): 
        self.result += num
        print("add함수 호출됨")

        return self.result

In [148]:
cal1=Calculator() #클래스->객체 생성
cal2=Calculator()

생성자 호출됨
생성자 호출됨


In [149]:
cal1.add(3)

add함수 호출됨


3

In [150]:
cal1.add(4)

add함수 호출됨


7

In [151]:
cal2.add(2)

add함수 호출됨


2

In [153]:
cal2.add(4)

add함수 호출됨


6

In [268]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [269]:
torch.manual_seed(1)

In [270]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [271]:
x_train.shape

torch.Size([3, 1])

In [272]:
W=torch.zeros(1, requires_grad=True) #requires_grad=True는 W는 업데이트가되어지는 변수다

In [273]:
W

tensor([0.], requires_grad=True)

In [274]:
b=torch.zeros(1, requires_grad=True) #requires_grad=True는 b는 업데이트가되어지는 변수다

In [275]:
#초기 모델 가설함수: y= 0 * x + 0
# hx=W * x_train + b

In [276]:
# hx

In [277]:
# cost

# cost=torch.mean((hx - y_train)**2)
# cost


In [278]:
# optimizer=optim.SGD([W,b],lr=0.01)

In [279]:
# optimizer.zero_grad() #미분을 해서 구한 기울기를 0으로 초기화해줌 
# cost.backward() #W,b에 대한 기울기가 계산
# optimizer.step() #W,b에 대한 업데이트

In [280]:
optimizer=optim.SGD([W,b],lr=0.01)
for epoch in range(2000):
    hx=W * x_train + b
    cost=torch.mean((hx - y_train)**2)
    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌,안해주면 이전에 해준기울기가 계속더해짐
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    if epoch%100 ==0:
        print(epoch,  W.item(), b.item(), cost.item())

0 0.18666668236255646 0.07999999821186066 18.66666603088379
100 1.7456912994384766 0.5780722498893738 0.04817060008645058
200 1.80009925365448 0.4544214904308319 0.029766537249088287
300 1.8428597450256348 0.35721680521965027 0.018393920734524727
400 1.876473307609558 0.28080499172210693 0.011366334743797779
500 1.9028971195220947 0.22073803842067719 0.007023668382316828
600 1.9236682653427124 0.1735200434923172 0.00434019835665822
700 1.9399964809417725 0.13640251755714417 0.0026819754857569933
800 1.952831506729126 0.10722480714321136 0.0016572937602177262
900 1.9629212617874146 0.0842885971069336 0.0010241125710308552
1000 1.9708527326583862 0.06625857204198837 0.0006328357267193496
1100 1.977087378501892 0.05208539217710495 0.0003910581872332841
1200 1.9819889068603516 0.04094360023736954 0.0002416476490907371
1300 1.9858416318893433 0.032185304909944534 0.00014932315389160067
1400 1.9888702630996704 0.025300635024905205 9.227206464856863e-05
1500 1.991250991821289 0.01988868787884

In [281]:
W #W:2 W의기울기

tensor([1.9974], requires_grad=True)

In [282]:
b #b:0

tensor([0.0060], requires_grad=True)

In [283]:
W.item()
b.item()

0.005984552204608917

In [284]:
W.item()*5 + b.item() #5는 임의로입력한값 예측값 구하려고

9.992821462452412

In [285]:
w = torch.tensor(2.0, requires_grad=True) #스칼라값 2를갖는
#requires_grad=True는 기울기를 구해서 저장하겠다는 의미

In [286]:
y=w**2

In [287]:
y

tensor(4., grad_fn=<PowBackward0>)

In [288]:
z=2*y+5

In [289]:
z

tensor(13., grad_fn=<AddBackward0>)

In [290]:
z.backward()

In [291]:
w.grad # z수식을w로 미분한 값

tensor(8.)

In [301]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [302]:
x1_train.shape

torch.Size([5, 1])

In [314]:
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [315]:
optimizer=optim.SGD([w1,w2,w3,b],lr=0.00001)#lr=1e-5랑같음 #0.01 <= lr <= 0.001 보편적인 값이지만 다를수있음 
#1* 10의 -5승 = 1 * 0.00001
for epoch in range(2000):
    hx=w1 * x1_train + w2 * x2_train+ w3 * x3_train + b
    cost=torch.mean((hx - y_train)**2)
    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    if epoch%10 ==0:
        print(epoch, w1.item(), w2.item(), w3.item(), b.item(), cost.item())

0 0.29401201009750366 0.2935999929904938 0.2973800003528595 0.0034199999645352364 29661.80078125
10 0.6673623323440552 0.6653894186019897 0.6745615601539612 0.007770418655127287 1.8976879119873047
20 0.6690528392791748 0.6658924221992493 0.6757622957229614 0.007798720151185989 1.6190385818481445
30 0.6696174144744873 0.6652738451957703 0.6758250594139099 0.007813933305442333 1.6119930744171143
40 0.6701772212982178 0.6646535396575928 0.6758841276168823 0.00782909244298935 1.6049734354019165
50 0.6707355380058289 0.6640350222587585 0.6759428381919861 0.00784424040466547 1.5979907512664795
60 0.6712925434112549 0.6634181141853333 0.676001250743866 0.00785937812179327 1.5910345315933228
70 0.6718481183052063 0.6628029942512512 0.6760593056678772 0.0078745037317276 1.5841312408447266
80 0.6724023222923279 0.6621896624565125 0.6761170625686646 0.007889614440500736 1.577264428138733
90 0.6729551553726196 0.6615779995918274 0.6761744022369385 0.007904715836048126 1.5704329013824463
100 0.6735

1170 0.7252631187438965 0.6046946048736572 0.6806232333183289 0.0094701386988163 1.0112825632095337
1180 0.7256854176521301 0.6042447090148926 0.680649995803833 0.00948407594114542 1.00746750831604
1190 0.7261066436767578 0.6037962436676025 0.6806762218475342 0.009498003870248795 1.0036699771881104
1200 0.7265268564224243 0.6033490300178528 0.6807023882865906 0.009511923417448997 0.999893844127655
1210 0.7269459962844849 0.6029030680656433 0.6807282567024231 0.00952583085745573 0.9961420297622681
1220 0.7273641228675842 0.6024583578109741 0.6807538866996765 0.009539728984236717 0.992401123046875
1230 0.7277812957763672 0.6020148396492004 0.6807793378829956 0.009553617797791958 0.9886852502822876
1240 0.728197455406189 0.601572573184967 0.6808045506477356 0.009567499160766602 0.9849969148635864
1250 0.7286126017570496 0.6011316180229187 0.6808295845985413 0.009581370279192924 0.9813085794448853
1260 0.7290266156196594 0.6006917953491211 0.680854320526123 0.009595233015716076 0.977646529

In [ ]:
# 발산하는 경우
# lr가 클때
# 입력데이터간의 편차가 심한 경우

In [316]:
w1.item()*90 + w2.item()*90 + w3.item()*90 + b.item()
#예상 수능점수: 180.9572057966143

180.9572057966143

In [317]:
#                               X1   X2   X3
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [318]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [ ]:
# h(x) = xtrain    w    +  b
# (5x1)= (5x3)   (3x1)  +  b

In [319]:
#w1 = torch.zeros(1, requires_grad=True)
#w2 = torch.zeros(1, requires_grad=True)
#w3 = torch.zeros(1, requires_grad=True) #1의 의미 0이 1개다
W = torch.zeros((3,1), requires_grad=True) #3x1행렬 일때 (3,1)로 써준다
b = torch.zeros(1, requires_grad=True)

In [320]:
optimizer=optim.SGD([W,b],lr=0.00001)#lr=1e-5랑같음 #0.01 <= lr <= 0.001 보편적인 값이지만 다를수있음 

In [321]:
for epoch in range(2000):
    hx=x_train.matmul(W) + b #matmul
    cost=torch.mean((hx - y_train)**2)
    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    if epoch%100 ==0:
        print(epoch, cost.item())

0 29661.80078125
100 5.754572868347168
200 5.512386322021484
300 5.281667232513428
400 5.061906814575195
500 4.852423667907715
600 4.652731418609619
700 4.4622650146484375
800 4.280604362487793
900 4.107260704040527
1000 3.941852569580078
1100 3.7838993072509766
1200 3.6330528259277344
1300 3.4889779090881348
1400 3.351316452026367
1500 3.2197258472442627
1600 3.0939736366271973
1700 2.9737014770507812
1800 2.858673334121704
1900 2.748659133911133


In [322]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [323]:
torch.manual_seed(1)

In [324]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [325]:
model = nn.Linear(1,1) # 입력차원, 출력차원 ex) 1입력되면 2출력 2입력되면 4출력... 하나입력 하나출력

In [327]:
list(model.parameters()) #w, b 값
#초기 모델 : hx=0.5153 * x_train -0.4414

[Parameter containing:
 tensor([[0.5153]], requires_grad=True),
 Parameter containing:
 tensor([-0.4414], requires_grad=True)]

In [328]:
optimizer=torch.optim.SGD(model.parameters(), lr=0.01)

In [329]:
for epoch in range(2000):
    hx = model(x_train) #hx=x_train.matmul(W) + b
    cost = F.mse_loss(hx, y_train)   # cost=torch.mean((hx - y_train)**2)
    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    
    if epoch%100 ==0:
        print(epoch, cost.item())

0 13.103541374206543
100 0.00279058120213449
200 0.00172441138420254
300 0.0010655784280970693
400 0.0006584661896340549
500 0.0004068926500622183
600 0.0002514346851967275
700 0.00015537298168055713
800 9.601024794392288e-05
900 5.9327696362743154e-05
1000 3.66610438504722e-05
1100 2.2655576685792767e-05
1200 1.3999051589053124e-05
1300 8.65114816406276e-06
1400 5.346103989722906e-06
1500 3.3032331430149497e-06
1600 2.04174443751981e-06
1700 1.2618406799447257e-06
1800 7.801028800713539e-07
1900 4.823282324650791e-07


In [330]:
list(model.parameters())

[Parameter containing:
 tensor([[1.9994]], requires_grad=True),
 Parameter containing:
 tensor([0.0014], requires_grad=True)]

In [331]:
new_var =  torch.FloatTensor([[4.0]])

In [332]:
model(new_var)

tensor([[7.9989]], grad_fn=<AddmmBackward0>)

In [333]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [334]:
model=nn.Linear(3,1) #입력차원, 출력차원

In [335]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True),
 Parameter containing:
 tensor([0.3462], requires_grad=True)]

In [336]:
optimizer=torch.optim.SGD(model.parameters(), lr=1e-5)

In [337]:
for epoch in range(2000):
    hx = model(x_train) #hx=x_train.matmul(W) + b
    cost = F.mse_loss(hx, y_train)   # cost=torch.mean((hx - y_train)**2)
    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    
    if epoch%100 ==0:
        print(epoch, cost.item())

0 42134.70703125
100 5.960053443908691
200 5.654706954956055
300 5.365412712097168
400 5.091428756713867
500 4.831833839416504
600 4.585997104644775
700 4.353074550628662
800 4.132411003112793
900 3.9234554767608643
1000 3.7255024909973145
1100 3.5379719734191895
1200 3.360325574874878
1300 3.19205641746521
1400 3.0326738357543945
1500 2.881699562072754
1600 2.7386722564697266
1700 2.603201150894165
1800 2.4748456478118896
1900 2.353286027908325


In [338]:
new_var =  torch.FloatTensor([[90,90,90]])
model(new_var)

tensor([[181.3557]], grad_fn=<AddmmBackward0>)

In [339]:
list(model.parameters())

[Parameter containing:
 tensor([[0.8540, 0.8475, 0.3096]], requires_grad=True),
 Parameter containing:
 tensor([0.3568], requires_grad=True)]