In [1]:
import pandas as pd

In [2]:
movie_dataset=pd.read_csv("title.basics.tsv", delimiter="\t")

C:\Users\user\AppData\Local\Temp\ipykernel_11504\2654942221.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  movie_dataset=pd.read_csv("title.basics.tsv", delimiter="\t")


In [3]:
movie_dataset

tconst  titleType               primaryTitle  \
0         tt0000001      short                 Carmencita   
1         tt0000002      short     Le clown et ses chiens   
2         tt0000003      short             Pauvre Pierrot   
3         tt0000004      short                Un bon bock   
4         tt0000005      short           Blacksmith Scene   
...             ...        ...                        ...   
10240753  tt9916848  tvEpisode              Episode #3.17   
10240754  tt9916850  tvEpisode              Episode #3.19   
10240755  tt9916852  tvEpisode              Episode #3.20   
10240756  tt9916856      short                   The Wind   
10240757  tt9916880  tvEpisode  Horrid Henry Knows It All   

                      originalTitle isAdult startYear endYear runtimeMinutes  \
0                        Carmencita       0      1894      \N              1   
1            Le clown et ses chiens       0      1892      \N              5   
2                    Pauvre Pierrot       0      1892      \N              4   
3                       Un bon bock       0      1892      \N             12   
4                  Blacksmith Scene       0      1893      \N              1   
...                             ...     ...       ...     ...            ...   
10240753              Episode #3.17       0      2009      \N             \N   
10240754              Episode #3.19       0      2010      \N             \N   
10240755              Episode #3.20       0      2010      \N             \N   
10240756                   The Wind       0      2015      \N             27   
10240757  Horrid Henry Knows It All       0      2014      \N             10   

                              genres  
0                  Documentary,Short  
1                    Animation,Short  
2           Animation,Comedy,Romance  
3                    Animation,Short  
4                       Comedy,Short  
...                              ...  
10240753         Action,Drama,Family  
10240754         Action,Drama,Family  
10240755         Action,Drama,Family  
10240756                       Short  
10240757  Adventure,Animation,Comedy  

[10240758 rows x 9 columns]

In [4]:
movie_ratings=pd.read_csv("title.ratings.tsv", delimiter="\t")

In [5]:
movie_ratings

tconst  averageRating  numVotes
0        tt0000001            5.7      2002
1        tt0000002            5.8       269
2        tt0000003            6.5      1892
3        tt0000004            5.5       178
4        tt0000005            6.2      2679
...            ...            ...       ...
1359874  tt9916730            7.6        11
1359875  tt9916766            7.0        22
1359876  tt9916778            7.2        36
1359877  tt9916840            8.8         6
1359878  tt9916880            8.2         6

[1359879 rows x 3 columns]

In [6]:
movie_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10240758 entries, 0 to 10240757
Data columns (total 9 columns):
 #   Column          Dtype 
---  ------          ----- 
 0   tconst          object
 1   titleType       object
 2   primaryTitle    object
 3   originalTitle   object
 4   isAdult         object
 5   startYear       object
 6   endYear         object
 7   runtimeMinutes  object
 8   genres          object
dtypes: object(9)
memory usage: 703.2+ MB


In [7]:
movie_dataset['startYear']

0           1894
1           1892
2           1892
3           1892
4           1893
            ... 
10240753    2009
10240754    2010
10240755    2010
10240756    2015
10240757    2014
Name: startYear, Length: 10240758, dtype: object

In [10]:
movie_dataset=movie_dataset[:100]
movie_ratings=movie_ratings[:100]

In [19]:
movie_dataset=movie_dataset[['startYear','runtimeMinutes']]
movie_dataset

startYear runtimeMinutes
0       1894              1
1       1892              5
2       1892              4
3       1892             12
4       1893              1
..       ...            ...
95      1896              1
96      1896              1
97      1896              1
98      1896              1
99      1896              1

[100 rows x 2 columns]

In [14]:
movie_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   startYear       100 non-null    object
 1   runtimeMinutes  100 non-null    object
dtypes: object(2)
memory usage: 1.7+ KB


In [15]:
movie_dataset.startYear.value_counts()

1896    67
1895    18
1894     6
1892     3
1897     3
1898     2
1893     1
Name: startYear, dtype: int64

In [16]:
movie_dataset.runtimeMinutes.value_counts()

\N    56
1     38
5      1
4      1
12     1
45     1
2      1
3      1
Name: runtimeMinutes, dtype: int64

In [ ]:
# movie_dataset의 모든 데이터 타입을 정수로 변환하세요.
# \N 은 최빈수인 1로 일괄 변경해주세요.

In [17]:
movie_dataset.runtimeMinutes[movie_dataset.runtimeMinutes.str.contains('N')]=1
movie_dataset.astype('int')

# movie_dataset.runtimeMinutes.replace("\\N","1", inplace=True)
# movie_dataset=movie_dataset.astype(int)

C:\Users\user\AppData\Local\Temp\ipykernel_11504\3725414313.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_dataset.runtimeMinutes[movie_dataset.runtimeMinutes.str.contains('N')]=1


startYear  runtimeMinutes
0        1894               1
1        1892               5
2        1892               4
3        1892              12
4        1893               1
..        ...             ...
95       1896               1
96       1896               1
97       1896               1
98       1896               1
99       1896               1

[100 rows x 2 columns]

In [21]:
#movie_dataset['runtimeMinutes'][movie_dataset['runtimeMinutes'] == '\\N']
#movie_dataset.runtimeMinutes[movie_dataset.runtimeMinutes.str.contains('N')]=1
#movie_dataset.runtimeMinutes.replace(to_replace = '\\N', value = '1', inplace = True)
#movie_dataset.runtimeMinutes.replace("\\N","1", inplace=True)
movie_dataset[movie_dataset.runtimeMinutes=='\\N']
movie_dataset.loc[movie_dataset.runtimeMinutes=='\\N', 'runtimeMinutes']=1

In [24]:
#movie_dataset.startYear=movie_dataset.startYear.astype('int64')
movie_dataset.runtimeMinutes.astype('int64')
movie_dataset['runtimeMinutes'][movie_dataset['runtimeMinutes'] == '\\N'] = 1

movie_dataset = movie_dataset.astype('int')

In [25]:
movie_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   startYear       100 non-null    int32
 1   runtimeMinutes  100 non-null    int32
dtypes: int32(2)
memory usage: 932.0 bytes


In [26]:
movie_ratings

tconst  averageRating  numVotes
0   tt0000001            5.7      2002
1   tt0000002            5.8       269
2   tt0000003            6.5      1892
3   tt0000004            5.5       178
4   tt0000005            6.2      2679
..        ...            ...       ...
95  tt0000097            4.9        34
96  tt0000098            5.2        37
97  tt0000099            4.6        33
98  tt0000100            4.8        55
99  tt0000101            4.5        29

[100 rows x 3 columns]

In [28]:
movie_ratings=movie_ratings.averageRating
movie_ratings

0     5.7
1     5.8
2     6.5
3     5.5
4     6.2
     ... 
95    4.9
96    5.2
97    4.6
98    4.8
99    4.5
Name: averageRating, Length: 100, dtype: float64

In [30]:
movie_dataset
#1892, 2 => ratings?
#2020, 6 => ratings?
#1900, 1 => ratings?
#k=5


startYear  runtimeMinutes
0        1894               1
1        1892               5
2        1892               4
3        1892              12
4        1893               1
..        ...             ...
95       1896               1
96       1896               1
97       1896               1
98       1896               1
99       1896               1

[100 rows x 2 columns]

In [31]:
from sklearn.neighbors import KNeighborsRegressor

In [32]:
model=KNeighborsRegressor(n_neighbors=5, weights='distance')

In [35]:
model.fit(movie_dataset, movie_ratings)

KNeighborsRegressor(weights='distance')

In [37]:
#1892, 2 => ratings?
model.predict([[1892,2], [2020, 6], [1900, 1 ]])
#2020, 6 => ratings?
#1900, 1 => ratings?
#k=5


C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([5.96542182, 5.09853186, 5.025     ])

In [ ]:
# 1.당뇨병 데이터셋
# - 2번~769번까지 데이터
# 트레인: 2~601번까지
# 테스트: 602~769번까지
    
# 2. 암 분류기
# 구글: UCI EDU DATASET -> Datasets - UCI Machine Learning Repository
# 전체 569건의 데이터
# 트레인 1~400
# 테스트 401~569

# 트레인 데이터 -> KNN 모델 -> 테스트 데이터
# 모델에 대한 정확도 출력(정확도 개선을 위한 다양한 노력)

In [173]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

In [174]:
diabetes=pd.read_csv("diabetes.csv")

In [175]:
diabetes.isnull().sum() #결측치 없음

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [176]:
diabetes_corr=diabetes.corr() #혈압과 피부두께의 상관관계가 낮다는 사실을 알 수 있음

In [177]:
diabetes_train=diabetes[2:602]
diabetes_test=diabetes[602:]

In [178]:
xtrain = diabetes_train.drop(columns= ['Outcome'])
ytrain = diabetes_train['Outcome']

In [179]:
xtest=diabetes_test.drop(columns=['Outcome'])

In [180]:
ytest=diabetes_test['Outcome']

In [181]:
scaler=StandardScaler()
scaler.fit(xtrain)

StandardScaler()

In [182]:
xtrain=scaler.transform(xtrain)

In [183]:
xtrain

array([[ 1.24434157,  1.92996053, -0.23507426, ..., -1.07248467,
         0.56827146, -0.10423463],
       [-0.83948403, -0.95362996, -0.13283102, ..., -0.47316847,
        -0.92965158, -1.03641425],
       [-1.1371734 ,  0.51884178, -1.4619932 , ...,  1.39969467,
         5.3616252 , -0.01949103],
       ...,
       [-0.83948403, -0.34010007, -1.56423644, ..., -1.09745618,
        -0.21776736, -0.61269624],
       [-0.83948403, -0.37077656,  0.99184468, ..., -0.59802601,
        -0.23853065, -0.78218345],
       [ 0.64896283, -0.7388945 , -3.5068581 , ..., -1.02254165,
        -0.86142934, -0.44320904]])

In [184]:
xtest=scaler.transform(xtest)

In [185]:
xtest

array([[-0.83948403,  0.12004735,  0.27614196, ..., -0.51062573,
        -1.12838592, -0.27372183],
       [ 0.9466522 ,  0.91763621,  0.48062845, ...,  0.41332008,
         0.62759515,  1.76012462],
       [ 0.05358409,  1.92996053, -3.5068581 , ..., -0.4357112 ,
        -0.79617329,  0.23473978],
       ...,
       [ 0.35127346,  0.02801787,  0.17389872, ..., -0.7103978 ,
        -0.69828921, -0.27372183],
       [-0.83948403,  0.18140034, -0.43956075, ..., -0.22345338,
        -0.38980605,  1.1669194 ],
       [-0.83948403, -0.83092398,  0.07165547, ..., -0.18599612,
        -0.49065631, -0.86692705]])

In [186]:
clf=KNeighborsClassifier()

In [187]:
params={'n_neighbors': [3,5,7,9,11,13,15,17,19]}

In [188]:
gs=GridSearchCV(clf, param_grid=params, cv=5, scoring='roc_auc')

In [189]:
gs.fit(xtrain,ytrain)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 7, 9, 11, 13, 15, 17, 19]},
             scoring='roc_auc')

In [190]:
print(gs.best_score_)
print(gs.best_estimator_)

0.792728851026165
KNeighborsClassifier(n_neighbors=15)


In [191]:
pred=gs.predict(xtest)
pred

array([0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [192]:
print(accuracy_score(ytest, pred))

print(confusion_matrix(ytest, pred))

0.7710843373493976
[[97  9]
 [29 31]]
