In [138]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer #문장을 단어별로 자르는것
from tensorflow.keras.preprocessing.sequence import pad_sequences #채우는거
from tensorflow.keras.utils import to_categorical #원핫인코딩 해주는함수

In [139]:
text='''
화려한 도시를 그리며 찾아왔네

그 곳은 춥고도 험한 곳

여기저기 헤매다 초라한 문턱에서

뜨거운 눈물을 먹는다

머나먼 길을 찾아 여기에 꿈을 찾아 여기에

괴롭고도 험한 이 길을 왔는데

이 세상 어디가 숲인지 어디가 늪인지

그 누구도 말을 않네

사람들은 저마다 고향을 찾아가네

나는 지금 홀로 남아서

빌딩 속을 헤매이다 초라한 골목에서

뜨거운 눈물을 먹는다

저기 저 별은 나의 마음을 알까 나의 꿈을 알까

괴로울 땐 슬픈 노래를 부른다

슬퍼질 땐 차라리 나 홀로 눈을 감고 싶어

고향의 향기 들으면서

저기 저 별은 나의 마음 알까 나의 꿈을 알까

괴로울 땐 슬픈 노래를 부른다

이 세상 어디가 숲인지 어디가 늪인지

그 누구도 말을 않네

슬퍼질 땐 차라리 나 홀로 눈을 감고 싶어

고향의 향기 들으면서

고향의 향기 들으면서
'''

In [140]:
print(text)


화려한 도시를 그리며 찾아왔네

그 곳은 춥고도 험한 곳

여기저기 헤매다 초라한 문턱에서

뜨거운 눈물을 먹는다

머나먼 길을 찾아 여기에 꿈을 찾아 여기에

괴롭고도 험한 이 길을 왔는데

이 세상 어디가 숲인지 어디가 늪인지

그 누구도 말을 않네

사람들은 저마다 고향을 찾아가네

나는 지금 홀로 남아서

빌딩 속을 헤매이다 초라한 골목에서

뜨거운 눈물을 먹는다

저기 저 별은 나의 마음을 알까 나의 꿈을 알까

괴로울 땐 슬픈 노래를 부른다

슬퍼질 땐 차라리 나 홀로 눈을 감고 싶어

고향의 향기 들으면서

저기 저 별은 나의 마음 알까 나의 꿈을 알까

괴로울 땐 슬픈 노래를 부른다

이 세상 어디가 숲인지 어디가 늪인지

그 누구도 말을 않네

슬퍼질 땐 차라리 나 홀로 눈을 감고 싶어

고향의 향기 들으면서

고향의 향기 들으면서



In [141]:
tokenizer = Tokenizer()

In [142]:
tokenizer.fit_on_texts([text])

In [143]:
tokenizer.word_index

{'어디가': 1,
 '나의': 2,
 '알까': 3,
 '땐': 4,
 '그': 5,
 '꿈을': 6,
 '이': 7,
 '홀로': 8,
 '고향의': 9,
 '향기': 10,
 '들으면서': 11,
 '험한': 12,
 '초라한': 13,
 '뜨거운': 14,
 '눈물을': 15,
 '먹는다': 16,
 '길을': 17,
 '찾아': 18,
 '여기에': 19,
 '세상': 20,
 '숲인지': 21,
 '늪인지': 22,
 '누구도': 23,
 '말을': 24,
 '않네': 25,
 '저기': 26,
 '저': 27,
 '별은': 28,
 '괴로울': 29,
 '슬픈': 30,
 '노래를': 31,
 '부른다': 32,
 '슬퍼질': 33,
 '차라리': 34,
 '나': 35,
 '눈을': 36,
 '감고': 37,
 '싶어': 38,
 '화려한': 39,
 '도시를': 40,
 '그리며': 41,
 '찾아왔네': 42,
 '곳은': 43,
 '춥고도': 44,
 '곳': 45,
 '여기저기': 46,
 '헤매다': 47,
 '문턱에서': 48,
 '머나먼': 49,
 '괴롭고도': 50,
 '왔는데': 51,
 '사람들은': 52,
 '저마다': 53,
 '고향을': 54,
 '찾아가네': 55,
 '나는': 56,
 '지금': 57,
 '남아서': 58,
 '빌딩': 59,
 '속을': 60,
 '헤매이다': 61,
 '골목에서': 62,
 '마음을': 63,
 '마음': 64}

In [144]:
vocab_size = len(tokenizer.word_index) + 1 #+1해준이유는 파이썬인덱스 0번부터인데 토큰화는 1번부터라서
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 65


In [145]:
#sequences = list()
#sequences

In [146]:
text

'\n화려한 도시를 그리며 찾아왔네\n\n그 곳은 춥고도 험한 곳\n\n여기저기 헤매다 초라한 문턱에서\n\n뜨거운 눈물을 먹는다\n\n머나먼 길을 찾아 여기에 꿈을 찾아 여기에\n\n괴롭고도 험한 이 길을 왔는데\n\n이 세상 어디가 숲인지 어디가 늪인지\n\n그 누구도 말을 않네\n\n사람들은 저마다 고향을 찾아가네\n\n나는 지금 홀로 남아서\n\n빌딩 속을 헤매이다 초라한 골목에서\n\n뜨거운 눈물을 먹는다\n\n저기 저 별은 나의 마음을 알까 나의 꿈을 알까\n\n괴로울 땐 슬픈 노래를 부른다\n\n슬퍼질 땐 차라리 나 홀로 눈을 감고 싶어\n\n고향의 향기 들으면서\n\n저기 저 별은 나의 마음 알까 나의 꿈을 알까\n\n괴로울 땐 슬픈 노래를 부른다\n\n이 세상 어디가 숲인지 어디가 늪인지\n\n그 누구도 말을 않네\n\n슬퍼질 땐 차라리 나 홀로 눈을 감고 싶어\n\n고향의 향기 들으면서\n\n고향의 향기 들으면서\n'

In [147]:
text.split('\n')

['',
 '화려한 도시를 그리며 찾아왔네',
 '',
 '그 곳은 춥고도 험한 곳',
 '',
 '여기저기 헤매다 초라한 문턱에서',
 '',
 '뜨거운 눈물을 먹는다',
 '',
 '머나먼 길을 찾아 여기에 꿈을 찾아 여기에',
 '',
 '괴롭고도 험한 이 길을 왔는데',
 '',
 '이 세상 어디가 숲인지 어디가 늪인지',
 '',
 '그 누구도 말을 않네',
 '',
 '사람들은 저마다 고향을 찾아가네',
 '',
 '나는 지금 홀로 남아서',
 '',
 '빌딩 속을 헤매이다 초라한 골목에서',
 '',
 '뜨거운 눈물을 먹는다',
 '',
 '저기 저 별은 나의 마음을 알까 나의 꿈을 알까',
 '',
 '괴로울 땐 슬픈 노래를 부른다',
 '',
 '슬퍼질 땐 차라리 나 홀로 눈을 감고 싶어',
 '',
 '고향의 향기 들으면서',
 '',
 '저기 저 별은 나의 마음 알까 나의 꿈을 알까',
 '',
 '괴로울 땐 슬픈 노래를 부른다',
 '',
 '이 세상 어디가 숲인지 어디가 늪인지',
 '',
 '그 누구도 말을 않네',
 '',
 '슬퍼질 땐 차라리 나 홀로 눈을 감고 싶어',
 '',
 '고향의 향기 들으면서',
 '',
 '고향의 향기 들으면서',
 '']

In [148]:
tokenizer.texts_to_sequences(['화려한 도시를 그리며 찾아왔네'])[0]

[39, 40, 41, 42]

In [149]:
sequences = list()
for line in text.split('\n'): #줄바꿈 문자를 기준으로 문장 토큰화
    encoded = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)
print('학습에 사용할 샘플의 개수: %d'%len(sequences))

학습에 사용할 샘플의 개수: 94


In [150]:
sequences

[[39, 40],
 [39, 40, 41],
 [39, 40, 41, 42],
 [5, 43],
 [5, 43, 44],
 [5, 43, 44, 12],
 [5, 43, 44, 12, 45],
 [46, 47],
 [46, 47, 13],
 [46, 47, 13, 48],
 [14, 15],
 [14, 15, 16],
 [49, 17],
 [49, 17, 18],
 [49, 17, 18, 19],
 [49, 17, 18, 19, 6],
 [49, 17, 18, 19, 6, 18],
 [49, 17, 18, 19, 6, 18, 19],
 [50, 12],
 [50, 12, 7],
 [50, 12, 7, 17],
 [50, 12, 7, 17, 51],
 [7, 20],
 [7, 20, 1],
 [7, 20, 1, 21],
 [7, 20, 1, 21, 1],
 [7, 20, 1, 21, 1, 22],
 [5, 23],
 [5, 23, 24],
 [5, 23, 24, 25],
 [52, 53],
 [52, 53, 54],
 [52, 53, 54, 55],
 [56, 57],
 [56, 57, 8],
 [56, 57, 8, 58],
 [59, 60],
 [59, 60, 61],
 [59, 60, 61, 13],
 [59, 60, 61, 13, 62],
 [14, 15],
 [14, 15, 16],
 [26, 27],
 [26, 27, 28],
 [26, 27, 28, 2],
 [26, 27, 28, 2, 63],
 [26, 27, 28, 2, 63, 3],
 [26, 27, 28, 2, 63, 3, 2],
 [26, 27, 28, 2, 63, 3, 2, 6],
 [26, 27, 28, 2, 63, 3, 2, 6, 3],
 [29, 4],
 [29, 4, 30],
 [29, 4, 30, 31],
 [29, 4, 30, 31, 32],
 [33, 4],
 [33, 4, 34],
 [33, 4, 34, 35],
 [33, 4, 34, 35, 8],
 [33, 4, 34, 

In [151]:
max_len = max(len(_) for _ in sequences) #모든 샘플에서 길이가 가장 긴 샘플의 길이 출력
print('샘플의 최대 길이: {}'.format(max_len))

샘플의 최대 길이: 9


In [152]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre') 
#패딩화 가장 긴 샘플을 기준으로 나머지 부족한만큼 채워줌 pre는 앞쪽에다 채워줌

In [153]:
sequences

array([[ 0,  0,  0,  0,  0,  0,  0, 39, 40],
       [ 0,  0,  0,  0,  0,  0, 39, 40, 41],
       [ 0,  0,  0,  0,  0, 39, 40, 41, 42],
       [ 0,  0,  0,  0,  0,  0,  0,  5, 43],
       [ 0,  0,  0,  0,  0,  0,  5, 43, 44],
       [ 0,  0,  0,  0,  0,  5, 43, 44, 12],
       [ 0,  0,  0,  0,  5, 43, 44, 12, 45],
       [ 0,  0,  0,  0,  0,  0,  0, 46, 47],
       [ 0,  0,  0,  0,  0,  0, 46, 47, 13],
       [ 0,  0,  0,  0,  0, 46, 47, 13, 48],
       [ 0,  0,  0,  0,  0,  0,  0, 14, 15],
       [ 0,  0,  0,  0,  0,  0, 14, 15, 16],
       [ 0,  0,  0,  0,  0,  0,  0, 49, 17],
       [ 0,  0,  0,  0,  0,  0, 49, 17, 18],
       [ 0,  0,  0,  0,  0, 49, 17, 18, 19],
       [ 0,  0,  0,  0, 49, 17, 18, 19,  6],
       [ 0,  0,  0, 49, 17, 18, 19,  6, 18],
       [ 0,  0, 49, 17, 18, 19,  6, 18, 19],
       [ 0,  0,  0,  0,  0,  0,  0, 50, 12],
       [ 0,  0,  0,  0,  0,  0, 50, 12,  7],
       [ 0,  0,  0,  0,  0, 50, 12,  7, 17],
       [ 0,  0,  0,  0, 50, 12,  7, 17, 51],
       [ 0

In [154]:
sequences = np.array(sequences)
x = sequences[:,:-1]
y = sequences[:,-1]

In [155]:
x

array([[ 0,  0,  0,  0,  0,  0,  0, 39],
       [ 0,  0,  0,  0,  0,  0, 39, 40],
       [ 0,  0,  0,  0,  0, 39, 40, 41],
       [ 0,  0,  0,  0,  0,  0,  0,  5],
       [ 0,  0,  0,  0,  0,  0,  5, 43],
       [ 0,  0,  0,  0,  0,  5, 43, 44],
       [ 0,  0,  0,  0,  5, 43, 44, 12],
       [ 0,  0,  0,  0,  0,  0,  0, 46],
       [ 0,  0,  0,  0,  0,  0, 46, 47],
       [ 0,  0,  0,  0,  0, 46, 47, 13],
       [ 0,  0,  0,  0,  0,  0,  0, 14],
       [ 0,  0,  0,  0,  0,  0, 14, 15],
       [ 0,  0,  0,  0,  0,  0,  0, 49],
       [ 0,  0,  0,  0,  0,  0, 49, 17],
       [ 0,  0,  0,  0,  0, 49, 17, 18],
       [ 0,  0,  0,  0, 49, 17, 18, 19],
       [ 0,  0,  0, 49, 17, 18, 19,  6],
       [ 0,  0, 49, 17, 18, 19,  6, 18],
       [ 0,  0,  0,  0,  0,  0,  0, 50],
       [ 0,  0,  0,  0,  0,  0, 50, 12],
       [ 0,  0,  0,  0,  0, 50, 12,  7],
       [ 0,  0,  0,  0, 50, 12,  7, 17],
       [ 0,  0,  0,  0,  0,  0,  0,  7],
       [ 0,  0,  0,  0,  0,  0,  7, 20],
       [ 0,  0, 

In [156]:
y

array([40, 41, 42, 43, 44, 12, 45, 47, 13, 48, 15, 16, 17, 18, 19,  6, 18,
       19, 12,  7, 17, 51, 20,  1, 21,  1, 22, 23, 24, 25, 53, 54, 55, 57,
        8, 58, 60, 61, 13, 62, 15, 16, 27, 28,  2, 63,  3,  2,  6,  3,  4,
       30, 31, 32,  4, 34, 35,  8, 36, 37, 38, 10, 11, 27, 28,  2, 64,  3,
        2,  6,  3,  4, 30, 31, 32, 20,  1, 21,  1, 22, 23, 24, 25,  4, 34,
       35,  8, 36, 37, 38, 10, 11, 10, 11])

In [157]:
y= to_categorical(y, num_classes=vocab_size)

In [158]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [159]:
vocab_size

65

In [160]:
embedding_dim = 20
hidden_units = 25
model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(SimpleRNN(hidden_units))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x, y, epochs=200, verbose=2)

Epoch 1/200
3/3 - 1s - loss: 4.1813 - accuracy: 0.0106 - 792ms/epoch - 264ms/step
Epoch 2/200
3/3 - 0s - loss: 4.1607 - accuracy: 0.0106 - 20ms/epoch - 7ms/step
Epoch 3/200
3/3 - 0s - loss: 4.1423 - accuracy: 0.0213 - 10ms/epoch - 3ms/step
Epoch 4/200
3/3 - 0s - loss: 4.1243 - accuracy: 0.0638 - 439us/epoch - 146us/step
Epoch 5/200
3/3 - 0s - loss: 4.1045 - accuracy: 0.0851 - 19ms/epoch - 6ms/step
Epoch 6/200
3/3 - 0s - loss: 4.0847 - accuracy: 0.0745 - 11ms/epoch - 4ms/step
Epoch 7/200
3/3 - 0s - loss: 4.0635 - accuracy: 0.0745 - 3ms/epoch - 975us/step
Epoch 8/200
3/3 - 0s - loss: 4.0405 - accuracy: 0.0745 - 16ms/epoch - 5ms/step
Epoch 9/200
3/3 - 0s - loss: 4.0166 - accuracy: 0.1064 - 0s/epoch - 0s/step
Epoch 10/200
3/3 - 0s - loss: 3.9935 - accuracy: 0.1064 - 16ms/epoch - 5ms/step
Epoch 11/200
3/3 - 0s - loss: 3.9695 - accuracy: 0.1277 - 14ms/epoch - 5ms/step
Epoch 12/200
3/3 - 0s - loss: 3.9451 - accuracy: 0.1702 - 2ms/epoch - 680us/step
Epoch 13/200
3/3 - 0s - loss: 3.9218 - accur

Epoch 105/200
3/3 - 0s - loss: 1.1937 - accuracy: 0.8511 - 14ms/epoch - 5ms/step
Epoch 106/200
3/3 - 0s - loss: 1.1739 - accuracy: 0.8511 - 2ms/epoch - 595us/step
Epoch 107/200
3/3 - 0s - loss: 1.1571 - accuracy: 0.8617 - 12ms/epoch - 4ms/step
Epoch 108/200
3/3 - 0s - loss: 1.1408 - accuracy: 0.8617 - 2ms/epoch - 568us/step
Epoch 109/200
3/3 - 0s - loss: 1.1261 - accuracy: 0.8511 - 0s/epoch - 0s/step
Epoch 110/200
3/3 - 0s - loss: 1.1103 - accuracy: 0.8511 - 17ms/epoch - 6ms/step
Epoch 111/200
3/3 - 0s - loss: 1.0937 - accuracy: 0.8617 - 0s/epoch - 0s/step
Epoch 112/200
3/3 - 0s - loss: 1.0812 - accuracy: 0.8617 - 16ms/epoch - 5ms/step
Epoch 113/200
3/3 - 0s - loss: 1.0604 - accuracy: 0.8617 - 0s/epoch - 0s/step
Epoch 114/200
3/3 - 0s - loss: 1.0483 - accuracy: 0.8617 - 16ms/epoch - 5ms/step
Epoch 115/200
3/3 - 0s - loss: 1.0330 - accuracy: 0.8617 - 0s/epoch - 0s/step
Epoch 116/200
3/3 - 0s - loss: 1.0182 - accuracy: 0.8617 - 14ms/epoch - 5ms/step
Epoch 117/200
3/3 - 0s - loss: 1.0061 

In [161]:
def sentence_generation(model, tokenizer, current_word, n):
    init_word = current_word
    sentence = ''
    
    #n 번 반복
    for _ in range(n):
        # 현재 단어에 대한 정수 인코딩과 패딩
        encoded = tokenizer.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=8, padding='pre')
        
        # 입력한 x(현재 단어)에 대해서 y를 예측하고 y(에측한단어)를 result에저장
        result = model.predict(encoded, verbose=0)
        result = np.argmax(result, axis=1)
        
        for word, index in tokenizer.word_index.items():
            # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면 break
            if index == result:
                break
                
        # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        current_word = current_word + ' ' + word
        
        # 예측 단어를 문장에 저장
        sentence = sentence + ' ' + word
        
    sentence = init_word + sentence
    return sentence

In [162]:
print(sentence_generation(model, tokenizer, '저기', 8))

저기 저 별은 나의 마음을 알까 나의 꿈을 알까
